theme: jekyll-theme-cayman

# Navigation (Optional)
title: "LDSC PROTOCOL"
description: "A comprehensive protcol to perform LDSC."
markdown: kramdown
kramdown:
  math_engine: mathjax

# Enable navigation links
include:
  - chapters/